const styles = {
  mainContainer: 'min-h-screen w-full flex flex-col items-center justify-center py-8 px-4 bg-white font-playfair',
  headingContainer: 'relative w-full flex flex-col items-center mb-2',
  backArrow: 'absolute left-4 top-0 text-[#008753] cursor-pointer z-10 font-playfair',
  pageTitle: 'mb-4 font-[700] text-[36px] leading-[100%] tracking-[-0.03em] text-[#008753] text-center font-playfair',
  progressContainer: 'w-full max-w-md flex items-center justify-between mb-6 font-playfair',
  progressBarWrapper: 'flex-1 h-1 bg-gray-200 rounded-full mr-4',
  progressBarActive: 'h-1 bg-[#008753] w-2/3 rounded-full',
  progressStepText: 'text-sm font-medium text-gray-500 font-playfair',
  formWrapper: 'w-full max-w-md space-y-6 font-playfair',
  labelClass: 'block mb-2 text-[14px] leading-[100%] tracking-[-0.03em] font-[500] text-[#1E1E1E] font-playfair',
  selectClass: 'w-full rounded-md border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#008753] text-[14px] leading-[100%] tracking-[-0.03em] font-[500] text-[#626060] font-playfair',
  inputClass: 'w-full rounded-md border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#008753] text-[14px] leading-[100%] tracking-[-0.03em] font-[500] text-[#1E1E1E] font-playfair',
  fileInputWrapper: 'relative flex-1 border border-gray-300 rounded-md px-3 py-2 text-sm text-gray-500 bg-gray-50 focus-within:outline-none focus-within:ring-2 focus-within:ring-[#008753] cursor-pointer font-playfair',
  noteText: 'mt-2 text-[12px] leading-[100%] tracking-[-0.03em] font-[400] italic text-[#1E1E1E] font-playfair',
  rowWrapper: 'flex space-x-4 font-playfair',
  halfWidth: 'w-1/2',
  grayPlaceholder: 'bg-[#E8E8E8]',
  buttonPrimary: 'w-full rounded-md bg-[#008753] text-white font-semibold py-2 hover:bg-[#006b42] focus:outline-none focus:ring-2 focus:ring-[#008753] font-playfair',
  spinnerOverlay: 'fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-20',
  spinner: 'h-12 w-12 border-4 border-t-4 border-gray-300 border-t-[#008753] rounded-full animate-spin',
  termsTextContainer: 'mt-6 text-center text-[10px] font-[800] leading-[100%] tracking-[-0.03em] underline text-[#1E1E1E] font-playfair',
  uploadHeading: 'block mb-2 text-[14px] leading-[100%] tracking-[-0.03em] font-[500] text-[#1E1E1E] font-playfair',
  uploadFieldWrapper: 'flex items-center space-x-3 font-playfair',
  uploadInputLabel: 'relative flex-1 border border-gray-300 rounded-md px-3 py-2 text-sm text-gray-500 bg-gray-50 focus-within:outline-none focus-within:ring-2 focus-within:ring-[#008753] cursor-pointer font-playfair',
  uploadIconContainer: 'absolute right-3 top-1/2 -translate-y-1/2 text-gray-400',
  uploadButtonStyle: 'px-4 py-2 bg-[#008753] text-white rounded-md hover:bg-[#006b42] focus:outline-none focus:ring-2 focus:ring-[#008753] font-playfair',
  uploadNoteStyle: 'mt-2 text-[12px] leading-[100%] tracking-[-0.03em] font-[400] italic text-[#1E1E1E] font-playfair'
};

export default styles;